export const imaginativePrompts = [
  "a steampunk penguin inventor working in Victorian London workshop",
  "a wise owl librarian organizing floating books in a tree library",
  "a group of cats performing a jazz concert in New Orleans",
  "a tired dragon working as a coffee barista in modern Seattle",
  "a mermaid food critic reviewing underwater restaurants",
  "a floating garden growing upside down in crystal bubbles",
  "a train made of clouds traveling through mountains of books",
  "an ancient temple growing from a giant bonsai tree in space",
  "a city built inside a massive violin, art nouveau style",
  "a market place where shadows are bought and sold, digital art",
  "a cyberpunk farmer tending to neon glowing plants in vertical gardens",
  "retro-futuristic ice cream truck floating through rings of Saturn",
  "android geisha serving digital tea in holographic teahouse",
  "floating islands with quantum computing labs powered by butterflies",
  "time-traveling mailman delivering letters between centuries, digital art",
  "dinosaurs attending a Victorian era ball in fancy dress",
  "ancient Egyptian pharaohs playing video games in an arcade",
  "medieval knights having a food truck festival",
  "Renaissance painters creating street art in modern Tokyo",
  "pirates running a cozy bed & breakfast in the Swiss Alps",
  "skyscrapers growing like bamboo from a misty valley",
  "coral reef forming the shape of an ancient Roman city",
  "northern lights forming a bridge between mountain peaks",
  "giant origami birds nesting in brutalist architecture",
  "trees growing into the shape of Gothic cathedral arches",
  "ukiyo-e style painting of robots playing baseball",
  "Monet-inspired scene of spaceships over lily ponds",
  "Pop Art treatment of ancient Greek mythology",
  "cubist interpretation of a busy subway station",
  "Renaissance portrait of a robot family",
  "musical instruments made entirely of flowing water",
  "a library where books are butterflies at rest",
  "kitchen appliances powered by tiny contained universes",
  "a garden where flowers bloom into tiny planets",
  "a typewriter that types in falling autumn leaves",
  "hot air balloons made of stained glass carrying cloud shepherds",
  "submarines designed like giant luminescent deep sea creatures",
  "flying carpets racing through cyber-bazaars",
  "trains running on tracks made of intertwined dragon bodies",
  "space elevators decorated like traditional totem poles",
  "dream architect designing castles in morning fog",
  "star tailor sewing constellations into new patterns",
  "cloud sculptor shaping weather into art installations",
  "time gardener pruning moments from history's timeline",
  "rainbow miner excavating colors from crystal caves",
  "street food vendor cooking with phoenix fire",
  "subway station where the trains are paper dragons",
  "laundromat where clothes are washed in liquid starlight",
  "rooftop garden growing musical flowers at sunset",
  "city park where shadows play games after dark",
];
